-- Create database if needed
CREATE DATABASE ph_news;

\c ph_news;

-- Create raw schema
CREATE SCHEMA IF NOT EXISTS raw;

-- Tables for each source
CREATE TABLE IF NOT EXISTS raw.abs_cbn_article_index_raw (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    retrieved_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    json_response JSONB NOT NULL
);

-- Table for ABS-CBN raw article details
CREATE TABLE IF NOT EXISTS raw.abs_cbn_article_detail_raw (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slugline_url TEXT NOT NULL,
    retrieved_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    json_response JSONB NOT NULL
);
